### ISSUE TITLE
Not showing some repos even though they're present on both github and deno.land

### ISSUE THREAD

**Issue by v1rtl** [yoshixmk/deno-x-ranking#13]
for example

gql module

deno.land/x: https://deno.land/x/gql@0.0.8

github: https://github.com/deno-libs/gql

but nothing in the search:

![Screenshot_2021-03-20-11-20-58-576_org mozilla firefox](https://user-images.githubusercontent.com/35937217/111863730-5deaaa00-896e-11eb-835a-cf55bb210075.jpg)

same for some other modules like `proxy_addr`

**Comment by v1rtl** [comment]
nevermind looks like it works again

**Comment by yoshixmk** [comment]
I found it. Often when the github action failed, the number of items that can be displayed decreases.

**Comment by v1rtl** [comment]
@yoshixmk nice for figuring this out! sometimes the bug happened, sometimes didn't

and I thought that it is registry fault but if the bug is here then prob it's possible to make a fix :P

**Comment by yoshixmk** [comment]
> @yoshixmk nice for figuring this out! sometimes the bug happened, sometimes didn't
> 
> and I thought that it is registry fault but if the bug is here then prob it's possible to make a fix :P

It ’s not a very clean method, [0.3.4](https://github.com/yoshixmk/deno-x-ranking/releases/tag/0.3.4) fixed. [fixed actions](https://github.com/yoshixmk/deno-x-ranking/actions/runs/699794235)
